source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DropdownMenu_Example', :exclusive => true do
  pod 'DropdownMenu', :path => '../'
end

target 'DropdownMenu_Tests', :exclusive => true do
  pod 'DropdownMenu', :path => '../'
end
